name: Deploy with API Key

on:
  push:
    branches: ["main"]  # Запускается при пуше в main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Используем последний Ubuntu

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Подставляем API-ключ из Secrets в HTML
      - name: Replace API Key
        run: |
          sed -i "s/__API_KEY__/${{ secrets.API_KEY }}/g" index.html

      # 3. (Опционально) Деплоим на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
